name: localiza_favoritos
description: Localiza favoritos

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter  
  sqflite:
  path:
  #flutter_osm_plugin: ^0.29.1+3
  #permission_handler: ^8.2.5
  flutter_osm_plugin: 
  permission_handler:
  flutter_map: any
  flutter_map_marker_cluster: any
  flutter_slidable: ^1.0.0
  osm_nominatim: ^2.0.1
  routing_client_dart: ^0.3.0
  flutter_bloc: ^6.0.0
  pull_to_refresh: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  location: ^4.3.0
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.2.0   
  geocoding: ^2.0.4
  latlong2: ^0.8.1
  flutter_compass: ^0.6.1
  splashscreen: ^1.3.5
  geocoder: ^0.2.1
  #animated_splash_screen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imagem/screenshot/screenPedro.png
    #- assets/tiles/10/231/
    #- assets/tiles/10/232/
    #- assets/tiles/10/233/
    #- assets/tiles/10/234/
    #- assets/tiles/10/235/
    #- assets/tiles/10/236/
    #- assets/tiles/10/237/
    #- assets/tiles/10/238/
    #- assets/tiles/10/239/
    #- assets/tiles/10/240/
    #- assets/tiles/10/241/
    #- assets/tiles/10/242/
    #- assets/tiles/10/243/
    #- assets/tiles/10/244/
    #- assets/tiles/10/245/
    #- assets/tiles/10/246/
    #- assets/tiles/10/247/
    #- assets/tiles/10/248/
    #- assets/tiles/10/249/
    #- assets/tiles/10/250/
    #- assets/tiles/10/251/
    #- assets/tiles/10/252/
    #- assets/tiles/10/253/
    #- assets/tiles/10/254/
    #- assets/tiles/10/255/
    #- assets/tiles/10/256/
    #- assets/tiles/10/257/
    #- assets/tiles/10/258/
    #- assets/tiles/10/259/
    #- assets/tiles/10/260/
    #- assets/tiles/10/261/
    #- assets/tiles/10/262/
    #- assets/tiles/10/263/
    #- assets/tiles/10/264/
    #- assets/tiles/10/265/
    #- assets/tiles/10/266/
    #- assets/tiles/10/267/
    #- assets/tiles/10/268/
    #- assets/tiles/10/269/
    #- assets/tiles/10/270/
    #- assets/tiles/10/271/
    #- assets/tiles/10/272/
    #- assets/tiles/10/273/
    #- assets/tiles/10/274/
    #- assets/tiles/10/275/
    #- assets/tiles/10/276/
    #- assets/tiles/10/277/
    #- assets/tiles/10/278/
    #- assets/tiles/10/279/
    #- assets/tiles/10/280/
    #- assets/tiles/10/281/
    #- assets/tiles/10/282/
    #- assets/tiles/10/283/
    #- assets/tiles/10/284/
    #- assets/tiles/10/285/
    #- assets/tiles/10/286/
    #- assets/tiles/10/287/
    #- assets/tiles/10/288/
    #- assets/tiles/10/289/
    #- assets/tiles/10/290/
    #- assets/tiles/10/291/
    #- assets/tiles/10/292/
    #- assets/tiles/10/293/
    #- assets/tiles/10/294/
    #- assets/tiles/10/295/
    #- assets/tiles/10/296/
    #- assets/tiles/10/297/
    #- assets/tiles/10/298/
    #- assets/tiles/10/299/
    #- assets/tiles/10/300/
    #- assets/tiles/10/301/
    #- assets/tiles/10/302/
    #- assets/tiles/10/303/
    #- assets/tiles/10/304/
    #- assets/tiles/10/305/
    #- assets/tiles/10/306/
    #- assets/tiles/10/307/
    #- assets/tiles/10/308/
    #- assets/tiles/10/309/
    #- assets/tiles/10/310/
    #- assets/tiles/10/311/
    #- assets/tiles/10/312/
    #- assets/tiles/10/313/
    #- assets/tiles/10/314/
    #- assets/tiles/10/315/
    #- assets/tiles/10/316/
    #- assets/tiles/10/317/
    #- assets/tiles/10/318/
    #- assets/tiles/10/319/
    #- assets/tiles/10/320/
    #- assets/tiles/10/321/
    #- assets/tiles/10/322/
    #- assets/tiles/10/323/
    #- assets/tiles/10/324/
    #- assets/tiles/10/325/
    #- assets/tiles/10/326/
    #- assets/tiles/10/327/
    #- assets/tiles/10/328/
    #- assets/tiles/10/329/
    #- assets/tiles/10/330/
    #- assets/tiles/10/331/
    #- assets/tiles/10/332/
    #- assets/tiles/10/333/
    #- assets/tiles/10/334/
    #- assets/tiles/10/335/
    #- assets/tiles/10/336/
    #- assets/tiles/10/337/
    #- assets/tiles/10/338/
    #- assets/tiles/10/339/
    #- assets/tiles/10/340/
    #- assets/tiles/10/341/
    #- assets/tiles/10/342/
    #- assets/tiles/10/343/
    #- assets/tiles/10/344/
    #- assets/tiles/10/345/
    #- assets/tiles/10/346/
    #- assets/tiles/10/347/
    #- assets/tiles/10/348/
    #- assets/tiles/10/349/
    #- assets/tiles/10/350/
    #- assets/tiles/10/351/
    #- assets/tiles/10/352/
    #- assets/tiles/10/353/
    #- assets/tiles/10/354/
    #- assets/tiles/10/355/
    #- assets/tiles/10/356/
    #- assets/tiles/10/357/
    #- assets/tiles/10/358/
    #- assets/tiles/10/359/
    #- assets/tiles/10/360/
    #- assets/tiles/10/361/
    #- assets/tiles/10/362/
    #- assets/tiles/10/363/
    #- assets/tiles/10/364/
    #- assets/tiles/10/365/
    #- assets/tiles/10/366/
    #- assets/tiles/10/367/
    #- assets/tiles/10/368/
    #- assets/tiles/10/369/
    #- assets/tiles/10/370/
    #- assets/tiles/10/371/
    #- assets/tiles/10/372/
    #- assets/tiles/10/373/
    #- assets/tiles/10/374/
    #- assets/tiles/10/375/
    #- assets/tiles/10/376/
    #- assets/tiles/10/377/
    #- assets/tiles/10/378/
    #- assets/tiles/10/379/
    #- assets/tiles/10/380/
    #- assets/tiles/10/381/
    #- assets/tiles/10/382/
    #- assets/tiles/10/383/
    #- assets/tiles/10/384/
    #- assets/tiles/10/385/
    #- assets/tiles/10/386/
    #- assets/tiles/10/387/
    #- assets/tiles/10/388/
    #- assets/tiles/10/389/
    #- assets/tiles/10/390/
    #- assets/tiles/10/391/
    #- assets/tiles/10/392/
    #- assets/tiles/10/393/
    #- assets/tiles/10/394/
    #- assets/tiles/10/395/
    #- assets/tiles/10/396/
    #- assets/tiles/10/397/
    #- assets/tiles/10/398/
    #- assets/tiles/10/399/
    #- assets/tiles/10/400/
    #- assets/tiles/10/401/
    #- assets/tiles/10/402/
    #- assets/tiles/10/403/
    #- assets/tiles/10/404/
    #- assets/tiles/10/405/
    #- assets/tiles/10/406/
    #- assets/tiles/10/407/
    #- assets/tiles/10/408/
    #- assets/tiles/10/409/
    #- assets/tiles/10/410/
    #- assets/tiles/10/411/
    #- assets/tiles/10/412/
    #- assets/tiles/10/413/
    #- assets/tiles/10/414/
    #- assets/tiles/10/415/
    #- assets/tiles/10/416/
    #- assets/tiles/10/417/
    #- assets/tiles/10/418/
    #- assets/tiles/10/419/
    #- assets/tiles/10/420/
    #- assets/tiles/10/421/
    #- assets/tiles/10/422/
    #- assets/tiles/10/423/
    #- assets/tiles/10/424/
    #- assets/tiles/10/425/
    #- assets/tiles/10/426/
    #- assets/tiles/10/427/
    #- assets/tiles/10/428/
    #- assets/tiles/10/429/
    #- assets/tiles/10/430/
    #- assets/tiles/10/431/
    #- assets/tiles/10/432/
    #- assets/tiles/10/433/
    #- assets/tiles/10/434/
    #- assets/tiles/10/435/
    #- assets/tiles/10/436/
    #- assets/tiles/10/437/
    #- assets/tiles/10/438/
    #- assets/tiles/10/439/
    #- assets/tiles/10/440/
    #- assets/tiles/10/441/
    #- assets/tiles/10/442/
    #- assets/tiles/10/443/
    #- assets/tiles/10/444/
    #- assets/tiles/10/445/
    #- assets/tiles/10/446/
    #- assets/tiles/10/447/
    #- assets/tiles/10/448/
    #- assets/tiles/10/449/
    #- assets/tiles/10/450/
    #- assets/tiles/10/451/
    #- assets/tiles/10/452/
    #- assets/tiles/10/453/
    #- assets/tiles/10/454/
    #- assets/tiles/10/455/
    #- assets/tiles/10/456/
    #- assets/tiles/10/457/
    #- assets/tiles/10/458/
    #- assets/tiles/10/459/
    #- assets/tiles/10/460/
    #- assets/tiles/10/461/
    #- assets/tiles/10/462/
    #- assets/tiles/10/463/
    #- assets/tiles/10/464/
    #- assets/tiles/10/465/
    #- assets/tiles/10/466/
    #- assets/tiles/10/467/
    #- assets/tiles/10/468/
    #- assets/tiles/10/469/
    #- assets/tiles/10/470/
    #- assets/tiles/10/471/
    #- assets/tiles/10/472/
    #- assets/tiles/10/473/
    #- assets/tiles/10/474/
    #- assets/tiles/10/475/
    #- assets/tiles/10/476/
    #- assets/tiles/10/477/
    #- assets/tiles/10/478/
    #- assets/tiles/10/479/
    #- assets/tiles/10/480/
    #- assets/tiles/10/481/
    #- assets/tiles/10/482/
    #- assets/tiles/10/483/
    #- assets/tiles/10/484/
    #- assets/tiles/10/485/
    #- assets/tiles/10/486/
    #- assets/tiles/10/487/
    #- assets/tiles/10/488/
    #- assets/tiles/10/489/
    #- assets/tiles/10/490/
    #- assets/tiles/10/491/
    #- assets/tiles/10/492/
    #- assets/tiles/10/493/
    #- assets/tiles/10/494/
    #- assets/tiles/10/495/
    #- assets/tiles/10/496/
    #- assets/tiles/10/497/
    #- assets/tiles/10/498/
    #- assets/tiles/10/499/
    #- assets/tiles/10/500/
    #- assets/tiles/10/501/
    #- assets/tiles/10/502/
    #- assets/tiles/10/503/
    #- assets/tiles/10/504/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

